# Generated by Django 5.1.6 on 2025-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blogpost_content_alter_blogpost_preview_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="publication_sign",
            field=models.BooleanField(
                default=False,
                help_text="Опубликовать пост?",
                verbose_name="Публикация поста",
            ),
        ),
    ]
