# Generated by Django 5.1.6 on 2025-03-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blogpost_publication_sign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="count_views",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров поста",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
