# Generated by Django 5.1.6 on 2025-03-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact_contactinfo_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение продукта",
                null=True,
                upload_to="products/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
